name: ProBending
main: net.bendercraft.spigot.probending.ProbendingPlugin
author: Nokorbis
description: Plugin to help for probending tournament management
version: 1.0.0
depend: [Bending]
softdepend: [Multiverse-Core]
load: POSTWORLD
commands:
   probending:
      description: Probending commands.
      aliases: [pb, probend]
      usage: /<command> ?
permissions:
   probending.admin.*:
       default: op
       description: Gives access to all Probending admin command
       children:
          probending.tournament.manage: true
          probending.admin.team.delete: true
          probending.admin.team.rename: true
          probending.admin.team.invite: true
          probending.admin.team.listmembers: true
          probending.command.team.list: true
   probending.tournament.manage:
      default: false
      description: Allows player to manage a probending tournament
   probending.team.manage:
      default: true
      description: Allows player to manage a probending team (create and invite for)
   probending.team.join:
      default: true
      description: Allows player to accept a team invitation
   probending.tournament.register:
      default: true
      description: Allows a player to register his team for a tournament
   probending.admin.team.delete:
      default: false
      description: Allows a player to delete teams, even ones of other players
   probending.admin.team.rename:
      default: false
      description: Allows a player to rename teams, even ones of other players
   probending.admin.team.invite:
      default: false
      descritpion: Allows an admin to invite a player in someone else's team.
   probending.command.team.list:
      default: true
      description: Allows a player to list all teams
   probending.admin.team.listmembers:
      default: true
      description: Allows an admin to list members of a team